#define MESCOLOR '#EB9C00'

// есть экшены связанные с объектами
PLAYER_ACTIONS = [
player addAction["<t color = MESCOLOR>Pickup Fuel can</t>", {TakingObject = true;deleteVehicle (nearestobjects [getpos player, [WS_FUELCAN],  5] select 0); hint "You have taken a fuel can."; player playmove "AinvPknlMstpSnonWnonDnon_1"; [WS_FUELCAN, ((nearestobjects [getpos player, [WS_FUELCAN],  5] select 0) getVariable "fuelcan")] call addToInventory; sleep 1.5; TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_FUELCAN],  5] select 0) < 4 && ((nearestobjects [getpos player, [WS_FUELCAN],  5] select 0) getVariable "fuelcan") == 1'],
player addAction["<t color = MESCOLOR>Pickup empty Fuel can</t>", {TakingObject = true;deleteVehicle (nearestobjects [getpos player, [WS_FUELCAN],  5] select 0); hint "You have taken an empty fuel can."; player playmove "AinvPknlMstpSnonWnonDnon_1"; [WS_FUELCAN, ((nearestobjects [getpos player, [WS_FUELCAN],  5] select 0) getVariable "fuelcan")] call addToInventory; sleep 1.5; TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_FUELCAN],  5] select 0) < 4 && ((nearestobjects [getpos player, [WS_FUELCAN],  5] select 0) getVariable "fuelcan") == 0'],

player addAction["<t color = MESCOLOR>Pickup Canned food</t>", {TakingObject = true;deleteVehicle (nearestobjects [getpos player, [WS_FOOD],  5] select 0); hint "You have taken some canned food."; player playmove "AinvPknlMstpSnonWnonDnon_1"; [WS_FOOD] call addToInventory; sleep 1.5; TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_FOOD],  5] select 0) < 5'],
player addAction["<t color = MESCOLOR>Take Canned food</t>", {TakingObject = true;_obj = nearestobjects [getpos player, [WS_FOOD_CONTAINER],  5] select 0; _left = _obj getVariable "foodcontainer"; hint format["You have taken some canned food.\n%1 left", _left - 1]; _obj setVariable ["foodcontainer", _left - 1, true]; player playmove "AinvPknlMstpSnonWnonDnon_1"; [WS_FOOD] call addToInventory; sleep 1.5;  TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_FOOD_CONTAINER],  5] select 0) < 5 && ((nearestobjects [getpos player, [WS_FOOD_CONTAINER],  5] select 0) getVariable "foodcontainer") > 0'],

player addAction["<t color = MESCOLOR>Pickup Money</t>", {TakingObject = true;deleteVehicle (nearestobjects [getpos player, [WS_MONEY],  5] select 0); player playmove "AinvPknlMstpSnonWnonDnon_1"; _money = nearestobjects [getpos player, [WS_MONEY],  5] select 0 getVariable "money"; hint format["You have picked up $%1", _money]; WSVAR_MONEY = WSVAR_MONEY + _money; sleep 1.5;  TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_MONEY],  5] select 0) < 5'],

player addAction["<t color = MESCOLOR>Pickup RepairKit</t>", {TakingObject = true;deleteVehicle (nearestobjects [getpos player, [WS_REPAIRKIT],  5] select 0); player playmove "AinvPknlMstpSnonWnonDnon_1";  WSVAR_REPAIRKIT = WSVAR_REPAIRKIT + 1; sleep 1.5;  TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_REPAIRKIT],  5] select 0) < 5'],

player addAction["<t color = MESCOLOR>Pickup bottle of water</t>", {TakingObject = true;deleteVehicle (nearestobjects [getpos player, [WS_WATER],  5] select 0); hint "You have taken a bottle of water."; player playmove "AinvPknlMstpSnonWnonDnon_1"; [WS_WATER] call addToInventory; sleep 1.5; TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_WATER],  5] select 0) < 5'],
player addAction["<t color = MESCOLOR>Take bottle of water</t>", {TakingObject = true;_obj = nearestobjects [getpos player, [WS_WATER_CONTAINER],  5] select 0; _left = _obj getVariable "watercontainer"; hint format["You have taken a bottle of water.\n%1 left", _left - 1]; _obj setVariable ["watercontainer", _left - 1, true]; player playmove "AinvPknlMstpSnonWnonDnon_1"; [WS_WATER] call addToInventory; sleep 1.5; TakingObject = nil;}, '',0,false,false,"",'isNil"TakingObject" && player distance (nearestobjects [getpos player, [WS_WATER_CONTAINER],  5] select 0) < 5 && ((nearestobjects [getpos player, [WS_WATER_CONTAINER],  5] select 0) getVariable "watercontainer") > 0']
];
// ... или не связанные
playerMenuId = player addAction [format ["<t color='#BE6300'>%1</t>", "Player Menu"], "call pm_fnc_init",[],-10,false,false,"","local player"];