WS_FOOD = "Land_Bag_EP1";
WS_FOOD_CONTAINER = "Land_Sacks_goods_F";

WS_WATER = "Land_Teapot_EP1";
WS_WATER_CONTAINER = "Land_CanisterPlastic_F";

WS_MONEY = "Land_Money_F";

WS_FUELCAN = "Land_CanisterFuel_F";

WS_REPAIRKIT = "Suitcase";

WS_OBJECTS = [WS_FOOD, WS_FOOD_CONTAINER, WS_WATER, WS_WATER_CONTAINER, WS_MONEY, WS_FUELCAN, WS_REPAIRKIT];
